// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Cane-V3-UI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onDropdownPatternChanged(lv_event_t * e);
void onButtonPrevClicked(lv_event_t * e);
void onButtonNextPatternClicked(lv_event_t * e);
void onAlwaysSwipeChecked(lv_event_t * e);
void onAlwaysSwipeUnchecked(lv_event_t * e);
void onColourWheelChanged(lv_event_t * e);
void onDropdownFirePaletteChanged(lv_event_t * e);
void onFireSparkingChanged(lv_event_t * e);
void onFireCoolingChanged(lv_event_t * e);
void onFlashModeStart(lv_event_t * e);
void onFlashModeEnd(lv_event_t * e);
void onFlashPressed(lv_event_t * e);
void onFlashReleased(lv_event_t * e);
void onLEDBrightnessChanged(lv_event_t * e);
void onGlitterChanged(lv_event_t * e);
void onHueDelayChanged(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
