// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Cane-V3-UI

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Container;
extern void ui_event_DropdownMode( lv_event_t * e);
extern lv_obj_t *ui_DropdownMode;
extern lv_obj_t *ui_ContainerNextPrev;
extern void ui_event_ButtonPrevPattern( lv_event_t * e);
extern lv_obj_t *ui_ButtonPrevPattern;
extern lv_obj_t *ui_Label9;
extern void ui_event_ButtonNextPattern( lv_event_t * e);
extern lv_obj_t *ui_ButtonNextPattern;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_ContainerSettingsFire;
extern lv_obj_t *ui_ContainerSparking;
extern lv_obj_t *ui_Label4;
extern void ui_event_SliderFireSparking( lv_event_t * e);
extern lv_obj_t *ui_SliderFireSparking;
extern lv_obj_t *ui_ContainerSparking1;
extern lv_obj_t *ui_Label3;
extern void ui_event_SliderFireCooling( lv_event_t * e);
extern lv_obj_t *ui_SliderFireCooling;
extern lv_obj_t *ui_ContainerLEDBrightness;
extern lv_obj_t *ui_Label1;
extern void ui_event_SliderLEDBrightness( lv_event_t * e);
extern lv_obj_t *ui_SliderLEDBrightness;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

