// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Cane-V3-UI

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_TabView1;
extern lv_obj_t *ui_TabStatus;
extern lv_obj_t *ui_Label2;
extern void ui_event_ButtonNextPattern( lv_event_t * e);
extern lv_obj_t *ui_ButtonNextPattern;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_TabSettings;
extern lv_obj_t *ui_Label1;
extern void ui_event_SliderLEDBrightness( lv_event_t * e);
extern lv_obj_t *ui_SliderLEDBrightness;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

